### ISSUE TITLE
Events to notify start and end of streams

### ISSUE THREAD

**Issue by piranna** [gulpjs/ordered-read-streams#16]
Add callbacks or events to notify when a stream start or has ended, to allow to inject data in the output stream (like shields or headers, for example).

**Comment by phated** [comment]
@piranna Can you give me some real-life scenarios for this?  I want to think about the abstraction a little before moving forward.

**Comment by piranna** [comment]
The GNU `head` command add a header line with the file path just before giving the file contents when called with several file arguments and the `--verbose` flag, so at [coreutils.js](https://github.com/piranna/coreutils.js) `head` implementation I need to know when a stream output is just about going to start to be able to print it. It can be used too to `.pipe()` the `process.stdin` in order to the streams when several of them request it when used the `-` filename several times.

**Comment by phated** [comment]
Closing in favor of #27
